# Generated by Django 5.0.4 on 2024-04-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_price_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
