# Generated by Django 5.0.4 on 2024-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderbook_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
