# Generated by Django 5.0.4 on 2024-06-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_content_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rating',
            new_name='app_rating_user_id_0dc794_idx',
            old_fields=('user', 'book'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
