# Generated by Django 5.0.4 on 2024-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_rating_user_book_app_rating_user_id_0dc794_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
