# Generated by Django 5.0.4 on 2024-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(default='no address yet', max_length=300),
        ),
    ]
